apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: "cluster-queue"
spec:
  namespaceSelector: {}
  queueingStrategy: BestEffortFIFO
  resourceGroups:
  - coveredResources: ["nvidia.com/gpu"]
    flavors:
    - name: "gpu-flavor"
      resources:
      - name: "nvidia.com/gpu"
        nominalQuota: 1
  - coveredResources: ["cpu"]
    flavors:
    - name: "cpu-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 6
